"""Generated by P64. Re-run VSCode setup to refresh project constants."""

from __future__ import annotations

# Scenes
SCENE_MAIN = "assets/scenes/main.scenep64"
SCENE_NAME_MAIN = "main"

SCENES = {
    "SCENE_MAIN": "assets/scenes/main.scenep64",
    "SCENE_NAME_MAIN": "main",
}

# Assets
ASSET_MTL_SAMPLE_LEVEL = "assets/sample_level.mtl"
ASSET_OBJ_SAMPLE_LEVEL = "assets/sample_level.obj"
ASSET_SCENEP64_MAIN = "assets/scenes/main.scenep64"
ASSET_PY_SPIN = "assets/scripts/spin.py"
ASSET_SHADER_STANDARD_TEXTURED = "assets/shaders/standard_textured.shader"

ASSETS = {
    "ASSET_MTL_SAMPLE_LEVEL": "assets/sample_level.mtl",
    "ASSET_OBJ_SAMPLE_LEVEL": "assets/sample_level.obj",
    "ASSET_SCENEP64_MAIN": "assets/scenes/main.scenep64",
    "ASSET_PY_SPIN": "assets/scripts/spin.py",
    "ASSET_SHADER_STANDARD_TEXTURED": "assets/shaders/standard_textured.shader",
}

# Input
INPUT_KEY_A = "a"
INPUT_KEY_ALT = "alt"
INPUT_KEY_B = "b"
INPUT_KEY_BACKSPACE = "backspace"
INPUT_KEY_C = "c"
INPUT_KEY_CTRL = "ctrl"
INPUT_KEY_D = "d"
INPUT_KEY_DELETE = "delete"
INPUT_KEY_DOWN = "down"
INPUT_KEY_E = "e"
INPUT_KEY_END = "end"
INPUT_KEY_ENTER = "enter"
INPUT_KEY_ESCAPE = "escape"
INPUT_KEY_F = "f"
INPUT_KEY_G = "g"
INPUT_KEY_H = "h"
INPUT_KEY_HOME = "home"
INPUT_KEY_I = "i"
INPUT_KEY_INSERT = "insert"
INPUT_KEY_J = "j"
INPUT_KEY_K = "k"
INPUT_KEY_L = "l"
INPUT_KEY_LEFT = "left"
INPUT_KEY_M = "m"
INPUT_KEY_META = "meta"
INPUT_KEY_N = "n"
INPUT_KEY_O = "o"
INPUT_KEY_P = "p"
INPUT_KEY_PAGE_DOWN = "page_down"
INPUT_KEY_PAGE_UP = "page_up"
INPUT_KEY_Q = "q"
INPUT_KEY_R = "r"
INPUT_KEY_RIGHT = "right"
INPUT_KEY_S = "s"
INPUT_KEY_SHIFT = "shift"
INPUT_KEY_SPACE = "space"
INPUT_KEY_T = "t"
INPUT_KEY_TAB = "tab"
INPUT_KEY_U = "u"
INPUT_KEY_UP = "up"
INPUT_KEY_V = "v"
INPUT_KEY_W = "w"
INPUT_KEY_X = "x"
INPUT_KEY_Y = "y"
INPUT_KEY_Z = "z"
INPUT_MOUSE_LEFT_MOUSE = "left_mouse"
INPUT_MOUSE_MIDDLE_MOUSE = "middle_mouse"
INPUT_MOUSE_RIGHT_MOUSE = "right_mouse"
INPUT_BUTTON_BACK = "back"
INPUT_BUTTON_EAST = "east"
INPUT_BUTTON_GUIDE = "guide"
INPUT_BUTTON_LEFT_SHOULDER = "left_shoulder"
INPUT_BUTTON_LEFT_STICK = "left_stick"
INPUT_BUTTON_NORTH = "north"
INPUT_BUTTON_RIGHT_SHOULDER = "right_shoulder"
INPUT_BUTTON_RIGHT_STICK = "right_stick"
INPUT_BUTTON_SOUTH = "south"
INPUT_BUTTON_START = "start"
INPUT_BUTTON_WEST = "west"
INPUT_AXIS_LEFT_TRIGGER = "left_trigger"
INPUT_AXIS_LEFT_X = "left_x"
INPUT_AXIS_LEFT_Y = "left_y"
INPUT_AXIS_RIGHT_TRIGGER = "right_trigger"
INPUT_AXIS_RIGHT_X = "right_x"
INPUT_AXIS_RIGHT_Y = "right_y"

INPUT_NAMES = [
    "a",
    "alt",
    "b",
    "backspace",
    "c",
    "ctrl",
    "d",
    "delete",
    "down",
    "e",
    "end",
    "enter",
    "escape",
    "f",
    "g",
    "h",
    "home",
    "i",
    "insert",
    "j",
    "k",
    "l",
    "left",
    "m",
    "meta",
    "n",
    "o",
    "p",
    "page_down",
    "page_up",
    "q",
    "r",
    "right",
    "s",
    "shift",
    "space",
    "t",
    "tab",
    "u",
    "up",
    "v",
    "w",
    "x",
    "y",
    "z",
    "left_mouse",
    "middle_mouse",
    "right_mouse",
    "back",
    "east",
    "guide",
    "left_shoulder",
    "left_stick",
    "north",
    "right_shoulder",
    "right_stick",
    "south",
    "start",
    "west",
    "left_trigger",
    "left_x",
    "left_y",
    "right_trigger",
    "right_x",
    "right_y",
]
