from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, TYPE_CHECKING

from p64.engine.files import is_metadata_file, is_scene_file
from p64.engine.input import PYGAME_AXIS_NAMES, PYGAME_BUTTON_NAMES, QT_KEY_NAMES, QT_MOUSE_BUTTONS

if TYPE_CHECKING:
    from p64.engine.project import Project


P64_TASK_LABELS = {
    "P64: Validate",
    "P64: Run",
    "P64: Open Editor",
    "P64: Bundle",
    "P64: Build",
}

P64_DEBUG_NAMES = {
    "P64: Run Project",
    "P64: Open Editor",
}


def setup_vscode_project(project: Project) -> None:
    """Create or refresh VSCode files for a P64 project."""

    vscode_dir = project.root / ".vscode"
    vscode_dir.mkdir(parents=True, exist_ok=True)
    _write_settings(project, vscode_dir / "settings.json")
    _write_tasks(vscode_dir / "tasks.json")
    _write_extensions(vscode_dir / "extensions.json")
    _write_launch(vscode_dir / "launch.json")
    _write_project_api(project)


def _write_settings(project: Project, path: Path) -> None:
    settings = _read_json_object(path)
    settings["python.analysis.extraPaths"] = _merge_list(
        settings.get("python.analysis.extraPaths"),
        _analysis_paths(project),
    )
    settings.setdefault("python.analysis.autoImportCompletions", True)
    settings.setdefault("python.analysis.typeCheckingMode", "basic")
    _write_json(path, settings)


def _analysis_paths(project: Project) -> list[str]:
    paths = [
        "assets/scripts",
        "packages/P64Generated/python",
        "libraries/P64Build/p64_source",
    ]
    source_root = Path(__file__).resolve().parents[2]
    try:
        paths.append(source_root.relative_to(project.root.resolve()).as_posix())
    except ValueError:
        paths.append(source_root.as_posix())
    return paths


def _write_tasks(path: Path) -> None:
    data = _read_json_object(path)
    data["version"] = "2.0.0"
    existing = [task for task in data.get("tasks", []) if isinstance(task, dict) and task.get("label") not in P64_TASK_LABELS]
    data["tasks"] = existing + _p64_tasks()
    _write_json(path, data)


def _p64_tasks() -> list[dict[str, Any]]:
    base = {
        "type": "shell",
        "command": "python",
        "options": {"cwd": "${workspaceFolder}"},
        "problemMatcher": [],
    }
    return [
        {**base, "label": "P64: Validate", "args": ["-m", "p64", "validate", "${workspaceFolder}"], "group": "test"},
        {**base, "label": "P64: Run", "args": ["-m", "p64", "run", "${workspaceFolder}"], "group": "build"},
        {**base, "label": "P64: Open Editor", "args": ["-m", "p64", "editor", "${workspaceFolder}"]},
        {**base, "label": "P64: Bundle", "args": ["-m", "p64", "bundle", "${workspaceFolder}"], "group": "build"},
        {**base, "label": "P64: Build", "args": ["-m", "p64", "build", "${workspaceFolder}"], "group": "build"},
    ]


def _write_extensions(path: Path) -> None:
    data = _read_json_object(path)
    data["recommendations"] = _merge_list(
        data.get("recommendations"),
        ["ms-python.python", "ms-python.vscode-pylance"],
    )
    _write_json(path, data)


def _write_launch(path: Path) -> None:
    data = _read_json_object(path)
    data["version"] = "0.2.0"
    existing = [
        config
        for config in data.get("configurations", [])
        if isinstance(config, dict) and config.get("name") not in P64_DEBUG_NAMES
    ]
    data["configurations"] = existing + [
        {
            "name": "P64: Run Project",
            "type": "debugpy",
            "request": "launch",
            "module": "p64",
            "args": ["run", "${workspaceFolder}"],
            "console": "integratedTerminal",
        },
        {
            "name": "P64: Open Editor",
            "type": "debugpy",
            "request": "launch",
            "module": "p64",
            "args": ["editor", "${workspaceFolder}"],
            "console": "integratedTerminal",
        },
    ]
    _write_json(path, data)


def _write_project_api(project: Project) -> None:
    project.project_api_dir.mkdir(parents=True, exist_ok=True)
    project.project_api_path.write_text(_project_api_source(project), encoding="utf-8")


def _project_api_source(project: Project) -> str:
    scenes = _scene_constants(project)
    assets = _asset_constants(project)
    lines = [
        '"""Generated by P64. Re-run VSCode setup to refresh project constants."""',
        "",
        "from __future__ import annotations",
        "",
        "# Scenes",
    ]
    lines.extend(_constant_lines(scenes) or ["# No scenes found"])
    lines.extend(["", "SCENES = {"])
    lines.extend(f'    "{key}": {_py_string(value)},' for key, value in scenes.items())
    lines.extend(["}", "", "# Assets"])
    lines.extend(_constant_lines(assets) or ["# No assets found"])
    lines.extend(["", "ASSETS = {"])
    lines.extend(f'    "{key}": {_py_string(value)},' for key, value in assets.items())
    lines.extend(["}", "", "# Input"])
    input_constants = _input_constants()
    lines.extend(_constant_lines(input_constants))
    lines.extend(["", "INPUT_NAMES = ["])
    lines.extend(f"    {_py_string(value)}," for value in input_constants.values())
    lines.extend(["]", ""])
    return "\n".join(lines)


def _scene_constants(project: Project) -> dict[str, str]:
    constants: dict[str, str] = {}
    for folder in [project.scenes_dir, project.legacy_scenes_dir]:
        if not folder.exists():
            continue
        for path in sorted(folder.rglob("*")):
            if is_scene_file(path):
                _add_constant(constants, "SCENE", path.stem, _project_relative(project, path))
                _add_constant(constants, "SCENE_NAME", path.stem, path.stem)
    return constants


def _asset_constants(project: Project) -> dict[str, str]:
    constants: dict[str, str] = {}
    if not project.assets_dir.exists():
        return constants
    for path in sorted(project.assets_dir.rglob("*")):
        if path.is_dir() or is_metadata_file(path) or path.name == "p64_project_api.py":
            continue
        prefix = "ASSET_" + path.suffix.lower().lstrip(".").upper() if path.suffix else "ASSET"
        _add_constant(constants, prefix, path.stem, _project_relative(project, path))
    return constants


def _input_constants() -> dict[str, str]:
    constants: dict[str, str] = {}
    for value in sorted(set(QT_KEY_NAMES.values()) | {chr(code).lower() for code in range(65, 91)}):
        _add_constant(constants, "INPUT_KEY", value, value)
    for value in sorted(QT_MOUSE_BUTTONS.values()):
        _add_constant(constants, "INPUT_MOUSE", value, value)
    for value in sorted(PYGAME_BUTTON_NAMES.values()):
        _add_constant(constants, "INPUT_BUTTON", value, value)
    for value in sorted(PYGAME_AXIS_NAMES.values()):
        _add_constant(constants, "INPUT_AXIS", value, value)
    return constants


def _add_constant(constants: dict[str, str], prefix: str, name: str, value: str) -> None:
    base = _constant_name(prefix, name)
    candidate = base
    index = 2
    while candidate in constants:
        if constants[candidate] == value:
            return
        candidate = f"{base}_{index}"
        index += 1
    constants[candidate] = value


def _constant_name(prefix: str, value: str) -> str:
    text = re.sub(r"[^0-9A-Za-z]+", "_", value).strip("_").upper()
    if not text:
        text = "VALUE"
    if text[0].isdigit():
        text = "_" + text
    return f"{prefix}_{text}"


def _constant_lines(constants: dict[str, str]) -> list[str]:
    return [f"{name} = {_py_string(value)}" for name, value in constants.items()]


def _py_string(value: str) -> str:
    return json.dumps(value)


def _project_relative(project: Project, path: Path) -> str:
    try:
        return path.resolve().relative_to(project.root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _merge_list(existing: Any, additions: list[str]) -> list[str]:
    values: list[str] = []
    if isinstance(existing, list):
        values.extend(str(item) for item in existing)
    for item in additions:
        if item not in values:
            values.append(item)
    return values


def _read_json_object(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}") from exc
    return data if isinstance(data, dict) else {}


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
